In [1]:
import numpy as np
import pandas as pd

################# 1 #################

In [2]:
# provo a creare un DataFrame partendo da un np.ndarray "alla Nicola"

# create empty DataFrame with 3 columns
dfcp = pd.DataFrame(columns=range(3))

# create 3 array of same lenght
a1 = np.random.randint(10, size=10)
b1 = np.arange(len(a1))
c1 = np.random.randint(low=100, high=150, size=10)

# stack the 3 arrays "column-wise" and append to DataFrame dfcp; print result
cp1 = np.dstack((a1,b1,c1)).reshape(-1,3)
dfcp = pd.DataFrame.append(dfcp, pd.DataFrame(cp1), ignore_index=True)
print(dfcp, '\n')

# repeat procedure
a2 = np.random.randint(10, size=10)
b2 = np.arange(len(a2))
c2 = np.random.randint(low=100, high=150, size=10)

# append new stacked array to DataFrame; print new result
cp2 = np.dstack((a2,b2,c2)).reshape(-1,3)
dfcp = pd.DataFrame.append(dfcp, pd.DataFrame(cp2), ignore_index=True)
print(dfcp)

   0  1    2
0  4  0  126
1  3  1  137
2  6  2  145
3  3  3  103
4  6  4  127
5  1  5  130
6  6  6  111
7  7  7  111
8  8  8  139
9  4  9  110 

    0  1    2
0   4  0  126
1   3  1  137
2   6  2  145
3   3  3  103
4   6  4  127
5   1  5  130
6   6  6  111
7   7  7  111
8   8  8  139
9   4  9  110
10  7  0  142
11  8  1  133
12  0  2  140
13  0  3  102
14  4  4  136
15  4  5  121
16  0  6  141
17  9  7  128
18  2  8  112
19  8  9  149


In [3]:
# create DataFrame in a more rational way

bigDF = pd.DataFrame()


new_df = pd.DataFrame()
# create 3 array of same lenght
x = np.random.randint(10, size=10)
y = np.arange(len(a1))
z = np.random.randint(low=100, high=150, size=10)

new_df['x'] = x
new_df['y'] = y
new_df['z'] = z

for idx in new_df['x']:
    print("idx: ", idx)
print(new_df)
bigDF = bigDF.append(new_df, ignore_index=True)

# create 3 array of same lenght
x0 = np.random.randint(10, size=10)
y0 = np.arange(len(a1))
z0 = np.random.randint(low=100, high=150, size=10)

new_df['x'] = x0
new_df['y'] = y0
new_df['z'] = z0

print(new_df, "\n")

bigDF = bigDF.append(new_df, ignore_index=False)
print(bigDF[['x','y']])
bigDF['x'] = np.zeros(len(bigDF['x']))
print(bigDF[['x','y']])


idx:  6
idx:  3
idx:  8
idx:  7
idx:  9
idx:  6
idx:  5
idx:  6
idx:  7
idx:  3
   x  y    z
0  6  0  111
1  3  1  127
2  8  2  128
3  7  3  149
4  9  4  116
5  6  5  127
6  5  6  107
7  6  7  116
8  7  8  113
9  3  9  100
   x  y    z
0  2  0  147
1  9  1  132
2  7  2  147
3  4  3  116
4  6  4  119
5  5  5  106
6  8  6  124
7  6  7  115
8  4  8  127
9  6  9  146 

   x  y
0  6  0
1  3  1
2  8  2
3  7  3
4  9  4
5  6  5
6  5  6
7  6  7
8  7  8
9  3  9
0  2  0
1  9  1
2  7  2
3  4  3
4  6  4
5  5  5
6  8  6
7  6  7
8  4  8
9  6  9
     x  y
0  0.0  0
1  0.0  1
2  0.0  2
3  0.0  3
4  0.0  4
5  0.0  5
6  0.0  6
7  0.0  7
8  0.0  8
9  0.0  9
0  0.0  0
1  0.0  1
2  0.0  2
3  0.0  3
4  0.0  4
5  0.0  5
6  0.0  6
7  0.0  7
8  0.0  8
9  0.0  9


In [4]:
for i, row in bigDF.iterrows():
    print(i, row['z'])

0 111.0
1 127.0
2 128.0
3 149.0
4 116.0
5 127.0
6 107.0
7 116.0
8 113.0
9 100.0
0 147.0
1 132.0
2 147.0
3 116.0
4 119.0
5 106.0
6 124.0
7 115.0
8 127.0
9 146.0


In [5]:
a = bigDF['y']
print(type(a))

<class 'pandas.core.series.Series'>


############################### 2 ##############################

In [6]:
a = np.ones([12,8])
b = np.zeros([5,8])
print(a, b)

[[1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]] [[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]


In [7]:
df = pd.DataFrame(columns=range(8))

In [8]:
df = df.append(pd.DataFrame(a))

In [9]:
df = df.append(pd.DataFrame(b), ignore_index=True)

In [10]:
df

0    1    2    3    4    5    6    7
0   1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0
1   1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0
2   1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0
3   1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0
4   1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0
5   1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0
6   1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0
7   1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0
8   1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0
9   1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0
10  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0
11  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0
12  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
13  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
14  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
15  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
16  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0

In [11]:
np.unique(df[2], return_counts=True)

(array([0., 1.]), array([ 5, 12]))

In [21]:
for x in df.iterrows():
    print(x)

TypeError: 'tuple' object does not support item assignment