In [1]:
import numpy as np

In [2]:
indexes = np.array([], dtype=np.int64).reshape(0,6)
print(indexes)

[]


In [3]:
indexes

array([], shape=(0, 6), dtype=int64)

In [4]:
a = np.zeros((5,6))

In [5]:
a

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [6]:
indexes = np.append(indexes, a, axis=0)

In [7]:
type(range(10))

range

In [8]:
indexes.shape

(5, 6)

In [9]:
b = np.ones((6,5))
for i in range(b.shape[0]):
    b[i,:] = i+1
print(b)

[[1. 1. 1. 1. 1.]
 [2. 2. 2. 2. 2.]
 [3. 3. 3. 3. 3.]
 [4. 4. 4. 4. 4.]
 [5. 5. 5. 5. 5.]
 [6. 6. 6. 6. 6.]]


In [10]:
indexes.T

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [11]:
lol = np.append(indexes.T, b, axis=0).T

In [12]:
print(lol)

[[0. 0. 0. 0. 0. 0. 1. 2. 3. 4. 5. 6.]
 [0. 0. 0. 0. 0. 0. 1. 2. 3. 4. 5. 6.]
 [0. 0. 0. 0. 0. 0. 1. 2. 3. 4. 5. 6.]
 [0. 0. 0. 0. 0. 0. 1. 2. 3. 4. 5. 6.]
 [0. 0. 0. 0. 0. 0. 1. 2. 3. 4. 5. 6.]]


In [13]:
b.shape

(6, 5)

In [14]:
b = b.reshape(-1,10)

In [15]:
b

array([[1., 1., 1., 1., 1., 2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3., 4., 4., 4., 4., 4.],
       [5., 5., 5., 5., 5., 6., 6., 6., 6., 6.]])

In [16]:
b.shape

(3, 10)

In [17]:
b.reshape(10,-1)

array([[1., 1., 1.],
       [1., 1., 2.],
       [2., 2., 2.],
       [2., 3., 3.],
       [3., 3., 3.],
       [4., 4., 4.],
       [4., 4., 5.],
       [5., 5., 5.],
       [5., 6., 6.],
       [6., 6., 6.]])

In [18]:
images = np.array([], dtype=np.float64).reshape(-1,100,100)

In [19]:
images

array([], shape=(0, 100, 100), dtype=float64)

In [21]:
crgs = np.empty((10,100,100), dtype=np.float64)

In [22]:
crgs

array([[[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]],

       [[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]],

       [[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]],

       ...,

       [[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0.

In [24]:
images = np.vstack((images, crgs))

In [27]:
len(images)

10

In [25]:
images.shape

(10, 100, 100)

In [28]:
labels = np.ones((10))

In [29]:
labels.shape

(10,)

In [35]:
np.block([images,labels])

ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 10 and the array at index 1 has size 1

In [46]:
lista = [[0,2]]*10

In [40]:
lista2 = [1]*2

In [47]:
lista

[[0, 2],
 [0, 2],
 [0, 2],
 [0, 2],
 [0, 2],
 [0, 2],
 [0, 2],
 [0, 2],
 [0, 2],
 [0, 2]]

In [42]:
lista+=lista2

In [43]:
lista

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1]

In [ ]:
np.