In [1]:
import numpy as np

In [2]:
a = np.arange(10)
b = np.arange(10,20)
c = np.arange(20,30)

In [3]:
a,b,c

(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19]),
 array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29]))

In [10]:
arrays = []

In [11]:
arrays.append(a)
arrays.append(b)
arrays.append(c)

In [12]:
arrays

[array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19]),
 array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29])]

In [13]:
arrays = np.array(arrays)

In [14]:
arrays

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [15]:
arrays.shape

(3, 10)

In [16]:
a.shape

(10,)